const user_input=require('readline-sync')
let user_name=user_input.question("enter user name  ")
let user_num=user_input.question("give the num  ")
console.log(user_name,"is user name")
console.log(parseInt (user_num))